return {
  'Kaiser-Yang/maplayer.nvim',
  config = function()
    local c = require('lightboat.condition')
    local h = require('lightboat.handler')
    require('maplayer').setup({
      -- stylua: ignore start
      { key = '1', mode = 'i', desc = 'Insert Markdown Title 1', condition = function() return c.filetype('markdown') and c.last_key(',') end, handler = h.markdown_title(1) },
      { key = '2', mode = 'i', desc = 'Insert Markdown Title 2', condition = function() return c.filetype('markdown') and c.last_key(',') end, handler = h.markdown_title(2) },
      { key = '3', mode = 'i', desc = 'Insert Markdown Title 3', condition = function() return c.filetype('markdown') and c.last_key(',') end, handler = h.markdown_title(3) },
      { key = '4', mode = 'i', desc = 'Insert Markdown Title 4', condition = function() return c.filetype('markdown') and c.last_key(',') end, handler = h.markdown_title(4) },
      { key = 's', mode = 'i', desc = 'Insert Markdown Separate Line', condition = function() return c.filetype('markdown') and c.last_key(',') end, handler = h.markdown_separate_line },
      { key = 'm', mode = 'i', desc = 'Insert Markdown Inline Math', condition = function() return c.filetype('markdown') and c.last_key(',') end, handler = h.markdown_math_inline_2 },
      { key = 't', mode = 'i', desc = 'Insert Markdown Code Line', condition = function() return c.filetype('markdown') and c.last_key(',') end, handler = h.markdown_code_line },
      { key = 'x', mode = 'i', desc = 'Insert Markdown Todo', condition = function() return c.filetype('markdown') and c.last_key(',') end, handler = h.markdown_todo },
      { key = 'a', mode = 'i', desc = 'Insert Markdown Link', condition = function() return c.filetype('markdown') and c.last_key(',') end, handler = h.markdown_link },
      { key = 'b', mode = 'i', desc = 'Insert Markdown Bold Text', condition = function() return c.filetype('markdown') and c.last_key(',') end, handler = h.markdown_bold },
      { key = 'd', mode = 'i', desc = 'Delete Current Line', condition = function() return c.filetype('markdown') and c.last_key(',') end, handler = h.markdown_delete_line },
      { key = 'i', mode = 'i', desc = 'Insert Markdown Italic Text', condition = function() return c.filetype('markdown') and c.last_key(',') end, handler = h.markdown_italic },
      { key = 'M', mode = 'i', desc = 'Insert Markdown Math Block', condition = function() return c.filetype('markdown') and c.last_key(',') end, handler = h.markdown_math_block },
      { key = 'c', mode = 'i', desc = 'Insert Markdown Code Block', condition = function() return c.filetype('markdown') and c.last_key(',') end, handler = h.markdown_code_block },
      { key = 'f', mode = 'i', desc = 'Markdown Goto Placeholder', condition = function() return c.filetype('markdown') and c.last_key(',') end, handler = h.markdown_goto_placeholder },
      { key = ';', mode = { 'n', 'x' }, desc = 'Repeat Last Motion Forward', handler = h.repmove_semicolon },
      { key = ',', mode = { 'n', 'x' }, desc = 'Repeat Last Motion Backward', handler = h.repmove_comma },
      { key = 'f', mode = { 'n', 'x' }, desc = 'Find Next Character', handler = h.repmove_builtin_f },
      { key = 'F', mode = { 'n', 'x' }, desc = 'Find Previous Character', handler = h.repmove_builtin_F },
      { key = 't', mode = { 'n', 'x' }, desc = 'Till Next Character', handler = h.repmove_builtin_t },
      { key = 'T', mode = { 'n', 'x' }, desc = 'Till Previous Character', handler = h.repmove_builtin_T },
      -- FIX: When inputting the key slowly, the default behavior still triggers
      { key = '[s', mode = { 'n', 'x', 'o' }, desc = 'Jump Previous Misspelled Word', handler = h.repmove_previous_misspelled },
      { key = ']s', mode = { 'n', 'x', 'o' }, desc = 'Jump Next Misspelled Word', handler = h.repmove_next_misspelled },
      { key = '[m', mode = { 'n', 'x', 'o' }, desc = 'Jump Previous Method Start', condition = c.treesitter_available, handler = h.repmove_previous_function_start },
      { key = ']m', mode = { 'n', 'x', 'o' }, desc = 'Jump Next Method Start', condition = c.treesitter_available, handler = h.repmove_next_function_start },
      { key = '[M', mode = { 'n', 'x', 'o' }, desc = 'Jump Previous Method End', condition = c.treesitter_available, handler = h.repmove_previous_function_end },
      { key = ']M', mode = { 'n', 'x', 'o' }, desc = 'Jump Next Method End', condition = c.treesitter_available, handler = h.repmove_next_function_end },
      { key = '[[', mode = { 'n', 'x', 'o' }, desc = 'Jump Previous Block Start', condition = c.treesitter_available, handler = h.repmove_previous_block_start },
      { key = ']]', mode = { 'n', 'x', 'o' }, desc = 'Jump Next Block Start', condition = c.treesitter_available, handler = h.repmove_next_block_start },
      { key = '[]', mode = { 'n', 'x', 'o' }, desc = 'Jump Previous Block End', condition = c.treesitter_available, handler = h.repmove_previous_block_end },
      { key = '][', mode = { 'n', 'x', 'o' }, desc = 'Jump Next Block End', condition = c.treesitter_available, handler = h.repmove_next_block_end },
      { key = '[i', mode = { 'n', 'x', 'o' }, desc = 'Jump Previous If Start', condition = c.treesitter_available, handler = h.rempove_previous_conditional_start },
      { key = ']i', mode = { 'n', 'x', 'o' }, desc = 'Jump Next If Start', condition = c.treesitter_available, handler = h.rempove_next_conditional_start },
      { key = '[I', mode = { 'n', 'x', 'o' }, desc = 'Jump Previous If End', condition = c.treesitter_available, handler = h.rempove_previous_conditional_end },
      { key = ']I', mode = { 'n', 'x', 'o' }, desc = 'Jump Next If End', condition = c.treesitter_available, handler = h.rempove_next_conditional_end },
      { key = '[f', mode = { 'n', 'x', 'o' }, desc = 'Jump Previous For Start', condition = c.treesitter_available, handler = h.repmove_previous_loop_start },
      { key = ']f', mode = { 'n', 'x', 'o' }, desc = 'Jump Next For Start', condition = c.treesitter_available, handler = h.repmove_next_loop_start },
      { key = '[F', mode = { 'n', 'x', 'o' }, desc = 'Jump Previous For End', condition = c.treesitter_available, handler = h.repmove_previous_loop_end },
      { key = ']F', mode = { 'n', 'x', 'o' }, desc = 'Jump Next For End', condition = c.treesitter_available, handler = h.repmove_next_loop_end },
      { key = '[r', mode = { 'n', 'x', 'o' }, desc = 'Jump Previous Return Start', condition = c.treesitter_available, handler = h.repmove_previous_return_start },
      { key = ']r', mode = { 'n', 'x', 'o' }, desc = 'Jump Next Return Start', condition = c.treesitter_available, handler = h.repmove_next_return_start },
      { key = '[R', mode = { 'n', 'x', 'o' }, desc = 'Jump Previous Return End', condition = c.treesitter_available, handler = h.repmove_previous_return_end },
      { key = ']R', mode = { 'n', 'x', 'o' }, desc = 'Jump Next Return End', condition = c.treesitter_available, handler = h.repmove_next_return_end },
      { key = '[c', mode = { 'n', 'x', 'o' }, handler = h.repmove_previous_class_start, desc = 'Jump Previous Class Start' },
      { key = ']c', mode = { 'n', 'x', 'o' }, handler = h.repmove_next_class_start, desc = 'Jump Next Class Start' },
      { key = '[C', mode = { 'n', 'x', 'o' }, handler = h.repmove_previous_class_end, desc = 'Jump Previous Class End' },
      { key = ']C', mode = { 'n', 'x', 'o' }, handler = h.repmove_next_class_end, desc = 'Jump Next Class End' },
      { key = 'ae', mode = { 'o', 'x' }, desc = 'Around Edit', handler = h.around_file },
      { key = 'am', mode = { 'o', 'x' }, desc = 'Around Method', condition = c.treesitter_available, handler = h.around_function },
      { key = 'im', mode = { 'o', 'x' }, desc = 'Inside Method', condition = c.treesitter_available, handler = h.inside_function },
      { key = 'ab', mode = { 'o', 'x' }, desc = 'Around Block', condition = c.treesitter_available, handler = h.around_block },
      { key = 'ib', mode = { 'o', 'x' }, desc = 'Inside Block', condition = c.treesitter_available, handler = h.inside_block },
      { key = 'ai', mode = { 'o', 'x' }, desc = 'Around If', condition = c.treesitter_available, handler = h.around_conditional },
      { key = 'ii', mode = { 'o', 'x' }, desc = 'Inside If', condition = c.treesitter_available, handler = h.inside_conditional },
      { key = 'af', mode = { 'o', 'x' }, desc = 'Around For', condition = c.treesitter_available, handler = h.around_loop },
      { key = 'if', mode = { 'o', 'x' }, desc = 'Inside For', condition = c.treesitter_available, handler = h.inside_loop },
      { key = 'ar', mode = { 'o', 'x' }, desc = 'Around Return', condition = c.treesitter_available, handler = h.around_return },
      { key = 'ir', mode = { 'o', 'x' }, desc = 'Inside Return', condition = c.treesitter_available, handler = h.inside_return },
      { key = 'ac', mode = { 'o', 'x' }, desc = 'Around Class', condition = c.treesitter_available, handler = h.around_class },
      { key = 'ic', mode = { 'o', 'x' }, desc = 'Inside Class', condition = c.treesitter_available, handler = h.inside_class },
      { key = '<c-j>', mode = { 'i', 'c' }, desc = 'Select Next Completion Item', condition = c.completion_menu_visible, handler = h.next_completion_item },
      { key = '<c-k>', mode = { 'i', 'c' }, desc = 'Select Previous Completion Item', condition = c.completion_menu_visible, handler = h.previous_completion_item },
      { key = '<tab>', mode = 'i', desc = 'Snippet Forward', condition = c.snippet_active, handler = h.snippet_forward },
      { key = '<s-tab>', mode = 'i', desc = 'Snippet Backward', condition = c.snippet_active, handler = h.snippet_backward },
      { key = '<c-x>', mode = { 'i', 'c' }, desc = 'Show Completion', condition = c.completion_menu_not_visible, handler = h.show_completion },
      { key = '<c-x>', mode = { 'i', 'c' }, desc = 'Hide Completion', condition = c.completion_menu_visible,  handler = h.hide_completion },
      { key = '<c-y>', mode = { 'i', 'c' }, desc = 'Accept Completion Item', condition = c.completion_menu_visible, handler = h.accept_completion_item },
      { key = '<c-e>', mode = { 'i', 'c' }, desc = 'Cancel Completion', condition = c.completion_menu_visible, handler = h.cancel_completion },
      { key = '<c-u>', mode = 'i', desc = 'Scroll Documentation Up', condition = c.documentation_visible, handler = h.scroll_documentation_up, priority = 2 },
      { key = '<c-u>', mode = 'i', desc = 'Scroll Signature Up', condition = c.signature_visible, handler = h.scroll_signature_up, priority = 1 },
      { key = '<c-d>', mode = 'i', desc = 'Scroll Documentation Down', condition = c.documentation_visible, handler = h.scroll_documentation_down, priority = 2 },
      { key = '<c-d>', mode = 'i', desc = 'Scroll Signature Down', condition = c.signature_visible, handler = h.scroll_signature_down, priority = 1 },
      { key = '<c-s>', mode = 'i', desc = 'Show Signature Help', condition = c.signature_not_visible, handler = h.show_signature },
      { key = '<c-s>', mode = 'i', desc = 'Hide Signature Help', condition = c.signature_visible, handler = h.hide_signature },
      { key = '<leader>f', mode = 'n', desc = 'Async Format', handler = h.async_format },
      { key = '(', mode = 'i', desc = 'Autopairs', handler = h.auto_pair_wrap('('), replace_keycodes = false },
      { key = ')', mode = 'i', desc = 'Autopairs', handler = h.auto_pair_wrap(')'), replace_keycodes = false },
      { key = '[', mode = 'i', desc = 'Autopairs', handler = h.auto_pair_wrap('['), replace_keycodes = false },
      { key = ']', mode = 'i', desc = 'Autopairs', handler = h.auto_pair_wrap(']'), replace_keycodes = false },
      { key = '{', mode = 'i', desc = 'Autopairs', handler = h.auto_pair_wrap('{'), replace_keycodes = false },
      { key = '}', mode = 'i', desc = 'Autopairs', handler = h.auto_pair_wrap('}'), replace_keycodes = false },
      { key = '"', mode = 'i', desc = 'Autopairs', handler = h.auto_pair_wrap('"'), replace_keycodes = false },
      { key = "'", mode = 'i', desc = 'Autopairs', handler = h.auto_pair_wrap("'"), replace_keycodes = false },
      { key = '`', mode = 'i', desc = 'Autopairs', handler = h.auto_pair_wrap('`'), replace_keycodes = false },
      { key = '<cr>', mode = 'i', desc = 'Autopairs', handler = h.auto_pair_wrap('<cr>'), replace_keycodes = false },
      { key = '<bs>', mode = 'i', desc = 'Autopairs', handler = h.auto_pair_wrap('<bs>'), replace_keycodes = false },
      { key = '<m-e>', mode = 'i', desc = 'Autopairs Fastwarp', handler = h.auto_pair_wrap('<a-e>'), replace_keycodes = false },
      { key = '<m-E>', mode = 'i', desc = 'Autopairs Reverse Fastwarp', handler = h.auto_pair_wrap('<a-E>'), replace_keycodes = false },
      { key = '<m-)>', mode = 'i', desc = 'Autopairs Close', handler = h.auto_pair_wrap('<a-)>'), replace_keycodes = false },
      { key = '<space>', mode = 'i', desc = 'Autopairs Space', handler = h.auto_pair_wrap('<space>'), replace_keycodes = false },
      -- stylua: ignore end
    })
  end,
}
